# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
   
   schedule:
    # triggers  every day at 12:00 and 22:00 UTC+8:
    - cron:  '0 14 * * *'
    - cron:  '0 4 * * *'
    - cron: '*/5 * * * *'
   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: 
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run main.py
        run: python3 main.py
      - uses: stefanzweifel/git-auto-commit-action@v5
      
